# This is a basic workflow to publish a Twilio function with Github Actions

name: Aarambh Staging release

# Controls when the action will run.
on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "IN"
      environment_code: "STG"
      changelog: "Deploying individual account"
       