name: Aselo Beta deploy

on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "AS"
      environment_code: "STG"
      changelog: "Deploying individual account"