# This is a basic workflow to publish a Twilio function with Github Actions

name: Aselo Development release


on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "AS"
      environment_code: "DEV"
      changelog: "Deploying individual account"