# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

# This job lets you deploy the Aselo serverless functions to a single environment for a single helpline
name: Deploy Serverless to a single helpline/environment

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      helpline_code:
        description: The short (usually 2 character) upper case code used to identify the helpline internally, e.g. ZA, IN, BR.
        required: true
      environment_code:
        description: The short upper case code used to identify the environment internally, e.g. STG, PROD, DEV
        required: true
        type: choice
        default: STG
        options:
          - DEV
          - STG
          - PROD
      force_enable_operating_hours:
        type: boolean
        description: Forces operating hours to be enforced for this deployment (by default they are only enforced in PROD)
  workflow_call:
    inputs:
      helpline_code:
        required: true
        type: string
      environment_code:
        required: true
        type: string
      send-slack-message:
        description: Specifies if should send a Slack message at the end of successful run. Defaults to true
        required: false
        default: 'true'
        type: string
jobs:
  deploy-helplines:
    name: Run Deployment
    uses: ./.github/workflows/deploy-multiple-accounts.yml
    secrets: inherit
    with:
      helplines: '[ "${{ inputs.helpline }}" ]'
      environments: '[ "${{ inputs.environment_code }}" ]'
      force_enable_operating_hours: ${{ inputs.force_enable_operating_hours }}
      send_final_slack_message: 'false'
      send_slack_message_per_deploy: ${{ inputs.send-slack-message }}