# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

# This is a basic workflow to deploy Serverless to all helpline staging environments

name: Deploy Serverless to all Staging Accounts

on:
  workflow_dispatch:

jobs:
  configure:
    name: Load Configuration
    runs-on: ubuntu-latest
    outputs:
      staging_helplines: ${{ steps.read-config.outputs.staging_helplines }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: read-config
        run: |
          content=`cat ./.github/workflows/config/staging-helplines.json`
          echo "staging_helplines=content" >> $GITHUB_OUTPUT
  deploy-helplines:
    name: Run All Staging Deployments
    needs: configure
    uses: ./.github/workflows/deploy-multiple-accounts.yml
    secrets: inherit
    with:
      helplines: ${{ needs.configure.outputs.staging_helplines }}
      environments: '[ "STG" ]'

