# This is a basic workflow to publish a Twilio function with Github Actions

name: Flex 2.0 Staging deplioy

on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "F2"
      environment_code: "STG"
      changelog: "Deploying individual account"