# This is a basic workflow to publish a Twilio function with Github Actions

name: Te Guío Colombia Production deploy

on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "CO"
      environment_code: "PROD"
      changelog: "Deploying individual account"