# This is a basic workflow to publish a Twilio function with Github Actions

name: Revenge Porn Helpline Staging release

on:
  workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: "UK"
      environment_code: "STG"
      changelog: "Deploying individual account"